services:
  speech-to-text-api:
    image: ggwozdz/speech-to-text-api:latest
    container_name: speech-to-text-api
    restart: always
    environment:
      - LOG_LEVEL=INFO
      - DEVICE=cpu
      - FILE_UPLOAD_PATH=uploaded_files
      - DELETE_FILES_AFTER_TRANSCRIPTION=true
      - FASTAPI_HOST=0.0.0.0
      - FASTAPI_PORT=9001
      - MODEL_IDLE_TIMEOUT=60
      - SPEECH_TO_TEXT_MODEL_NAME=openai/whisper
      - SPEECH_TO_TEXT_MODEL_TYPE=turbo
      - SPEECH_TO_TEXT_MODEL_DOWNLOAD_PATH=transcription_models
      - TRANSLATION_MODEL_NAME=facebook/seamless-m4t-v2-large
      - TRANSLATION_MODEL_DOWNLOAD_PATH=translation_models
    ports:
      - "9001:9001"
    volumes:
      - ${DOCKER_VOLUMES}/speech-to-text-api/data/transcription_models:/app/transcription_models
      - ${DOCKER_VOLUMES}/speech-to-text-api/data/translation_models:/app/translation_models
      - ${DOCKER_VOLUMES}/speech-to-text-api/data/uploaded_files:/app/uploaded_files

volumes:
  speech-to-text-api-data:
    driver_opts:
      type: none
      device: ${DOCKER_VOLUMES}/speech-to-text-api/data
      o: bind
